# Generated by Django 5.0.3 on 2024-03-20 19:52

import django.core.validators
import student_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_alter_student_locker_combination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='locker_combination',
            field=models.CharField(default='12-12-12', validators=[django.core.validators.MaxLengthValidator(8), student_app.validators.validate_combination]),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(validators=[django.core.validators.MaxLengthValidator(50), student_app.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='student',
            name='personal_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(max_length=254, unique=True, validators=[student_app.validators.validate_school_email]),
        ),
    ]
